// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisitRwanda.Models;

#nullable disable

namespace VisitRwanda.Migrations
{
    [DbContext(typeof(VisitRwandaContext))]
    [Migration("20250508235249_SeedCulturesFix")]
    partial class SeedCulturesFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VisitRwanda.Models.Culture", b =>
                {
                    b.Property<int>("CultureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CultureID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CultureID");

                    b.ToTable("Cultures");

                    b.HasData(
                        new
                        {
                            CultureID = 1,
                            Description = "Rwandan culture has many traditions including traditional Intore dancing, basketry and Umuganda.",
                            Image = "CultureTraditions.jpg",
                            Title = "Rwandan Culture and Traditions"
                        },
                        new
                        {
                            CultureID = 2,
                            Description = "Formerly the Presidential Palace Museum, this new museum displays contemporary artworks from Rwanda as well as abroad.It hosts temporary and travelling exhibitions alongside the permanent collection.",
                            Image = "RwandaArtMuseum.jpg",
                            Title = "Rwanda Art Museum"
                        },
                        new
                        {
                            CultureID = 3,
                            Description = "The Kigali Genocide Memorial at Gisozi is where 250,000 victims have been buried. This memorial also serves to educate about how the 1994 Genocide against the Tutsi took shape and examines genocide in the 20th century. ",
                            Image = "KigaliGenocide.jpg",
                            Title = "Kigali Genocide Memorial"
                        },
                        new
                        {
                            CultureID = 4,
                            Description = "The Kandt House Museum looks at colonialism in relation to Rwanda, set in the old house of the first colonial governor.",
                            Image = "KandtHouse.jpg",
                            Title = "Kandt House Museum"
                        },
                        new
                        {
                            CultureID = 5,
                            Description = "Though it would have been a pipe dream some years ago, today Kigali is cosmopolitan enough to host not one, but two fashion festivals every year, and for fashionistas and those on the cutting edge of style, they offer a fantastic opportunity to see the cultural fusion of western and Rwandan styles that the country’s finest designers negotiate and create daily. Kigali Fashion Week takes place every July, and hosts dozens of international, local, and upcoming young designers, while the Rwanda Cultural Fashion Week showcases even more local and international talent every September.",
                            Image = "FashionStyle.jpg",
                            Title = "Fashion & Style"
                        });
                });

            modelBuilder.Entity("VisitRwanda.Models.Destination", b =>
                {
                    b.Property<int>("DestinationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DestinationID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DestinationID");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationID = 1,
                            Description = "One of the oldest rainforests in Africa, Nyungwe is rich in biodiversity and spectacularly beautiful. The mountainous region is teaming with wildlife, including a small population of chimpanzees as well as 12 other species of primate.",
                            Image = "Nyungwe.jpg",
                            Location = "Southern Province",
                            Name = "Nyungwe National Park"
                        },
                        new
                        {
                            DestinationID = 2,
                            Description = "Home to the King's Palace a reconstruction of the traditional royal residence, a beautifully crafted thatched dwelling shaped like a beehive.",
                            Image = "Nyanza.jpg",
                            Location = "Southern Province",
                            Name = "Nyanza"
                        },
                        new
                        {
                            DestinationID = 3,
                            Description = "Part of Africa’s Great Rift Valley, Lake Kivu is dotted with islands and inlets along its shoreline, with charming beach resorts, spectacular vistas and plenty of opportunities for hiking and cycling.",
                            Image = "LakeKivu.jpg",
                            Location = "Western Province",
                            Name = "Lake Kivu"
                        },
                        new
                        {
                            DestinationID = 4,
                            Description = "The relatively warm and low‑lying plains of Akagera comprise savannah, woodland, wetland and a dozen lakes. In partnership with African Parks, we have reintroduced lions and rhinos, meaning once again visitors can hope to see the Big Five on safari drives.",
                            Image = "Akagera.jpg",
                            Location = "Eastern Province",
                            Name = "Akagera National Park"
                        },
                        new
                        {
                            DestinationID = 5,
                            Description = "“In the heart of Central Africa, so high up that you shiver more than you sweat,” wrote Dian Fossey. “Great, old volcanoes towering almost 15,000 feet, nearly covered with rich, green rainforest—the Virungas.”",
                            Image = "Volcanoes.jpg",
                            Location = "Northern Province",
                            Name = "Volcanoes National Park"
                        },
                        new
                        {
                            DestinationID = 6,
                            Description = "The capital city is pleasantly low key yet dynamic and progressive. It's green, clean and safe with meaningful culture and remarkable drive.",
                            Image = "Kigali.jpg",
                            Location = "Kigali",
                            Name = "Kigali"
                        });
                });

            modelBuilder.Entity("VisitRwanda.Models.Investment", b =>
                {
                    b.Property<int>("InvestmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvestmentID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvestmentID");

                    b.ToTable("Investments");
                });
#pragma warning restore 612, 618
        }
    }
}
